### ISSUE TITLE
error occurs while executing entry script

### ISSUE THREAD

**Issue by tangxiongfei** [aehyok/vue-qiankun#9]
index.js:187 [import-html-entry]: error occurs while executing entry script http://127.0.0.1:4000/js/app.js
exec @ index.js:187
schedule @ index.js:220
schedule @ index.js:225
(anonymous) @ index.js:231
(anonymous) @ index.js:230
Promise.then (async)
_execScripts @ index.js:161
execScripts @ index.js:294
_callee17$ @ loader.js:321
tryCatch @ regeneratorRuntime.js:86
(anonymous) @ regeneratorRuntime.js:66
(anonymous) @ regeneratorRuntime.js:117
fulfilled @ tslib.es6.js:71
Promise.then (async)
step @ tslib.es6.js:73
fulfilled @ tslib.es6.js:71
Promise.then (async)
step @ tslib.es6.js:73
fulfilled @ tslib.es6.js:71
Promise.then (async)
step @ tslib.es6.js:73
fulfilled @ tslib.es6.js:71
Promise.then (async)
step @ tslib.es6.js:73
(anonymous) @ tslib.es6.js:74
__awaiter @ tslib.es6.js:70
loadApp @ loader.js:230
_callee3$ @ apis.js:77
tryCatch @ regeneratorRuntime.js:86
(anonymous) @ regeneratorRuntime.js:66
(anonymous) @ regeneratorRuntime.js:117
fulfilled @ tslib.es6.js:71
Promise.then (async)
step @ tslib.es6.js:73
(anonymous) @ tslib.es6.js:74
__awaiter @ tslib.es6.js:70
app2 @ apis.js:62
(anonymous) @ load.js:39
Promise.then (async)
(anonymous) @ load.js:38
Promise.then (async)
z @ load.js:24
(anonymous) @ reroute.js:147
(anonymous) @ reroute.js:146
Promise.then (async)
g2 @ reroute.js:94
Lt @ reroute.js:66
rt @ navigation-events.js:91
(anonymous) @ navigation-events.js:105
changeLocation @ vue-router.esm-bundler.js:541
push @ vue-router.esm-bundler.js:580
finalizeNavigation @ vue-router.esm-bundler.js:3194
(anonymous) @ vue-router.esm-bundler.js:3070
Promise.then (async)
pushWithRedirect @ vue-router.esm-bundler.js:3041
push @ vue-router.esm-bundler.js:2969
jumpChildSystem @ Home.vue:53
onClick @ Home.vue:18
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
invoker @ runtime-dom.esm-bundler.js:369
app-errors.js:11 Uncaught TypeError: application 'webpack-app' died in status LOADING_SOURCE_CODE: Assignment to constant variable.
    at Proxy.eval (tableConfig.js?7847:164:1)
    at ./src/views/tableConfig.js (app.js:5540:1)
    at __webpack_require__ (app.js:864:30)
    at fn (app.js:161:20)
    at Proxy.eval (Table.vue?3f0e:15:1)
    at ../../node_modules/.pnpm/cache-loader@4.1.0_webpack@4.46.0/node_modules/cache-loader/dist/cjs.js?!../../node_modules/.pnpm/babel-loader@8.2.5_5ouqwanl7jnotevpn4w6qovjqm/node_modules/babel-loader/lib/index.js!../../node_modules/.pnpm/cache-loader@4.1.0_webpack@4.46.0/node_modules/cache-loader/dist/cjs.js?!../../node_modules/.pnpm/vue-loader@16.8.3_rrikhbkquxx6n2xidrow5h36l4/node_modules/vue-loader/dist/index.js?!./src/views/Table.vue?vue&type=script&lang=js (app.js:1677:1)
    at __webpack_require__ (app.js:864:30)
    at fn (app.js:161:20)
    at Proxy.eval (Table.vue?dd43:1:1)
    at ./src/views/Table.vue?vue&type=script&lang=js (app.js:5456:1)

**Comment by tangxiongfei** [comment]
apps/webpack-app-ts/src/views/tableConfig.js 

const listTest = []           =>              let listTest = []

**Comment by aehyok** [comment]
@tangxiongfei 大佬， 改完这里好了吗？
